import type { Locale } from "./i18n";
import { htmlLang, localePath, SITE_URL, SUPPORTED_LOCALES } from "./i18n";

export const ARTICLE_SLUGS = ["card-doodles", "lunchbox-notes", "journal-doodles"] as const;
export type ArticleSlug = (typeof ARTICLE_SLUGS)[number];
export type EditorialSegment = "blog" | "for-ai";

export const EDITORIAL_REVIEW = {
  sourceDate: "2026-09-23",
  demandSignals: [
    "card doodle ideas",
    "easy lunchbox note drawings",
    "simple journal doodles",
    "easy drawings to copy",
  ],
} as const;

export type EditorialArticle = {
  slug: ArticleSlug;
  title: string;
  description: string;
  eyebrow: string;
  intro: string;
  steps: readonly { heading: string; body: string }[];
  tipTitle: string;
  tipBody: string;
};

export type EditorialCopy = {
  blog: { eyebrow: string; title: string; description: string; readMore: string; back: string };
  forAi: { eyebrow: string; title: string; description: string; intro: string; useTitle: string; uses: readonly string[]; trial: string; privacy: string; start: string; blog: string };
  nav: { blog: string; forAi: string; app: string; related: string; tryDoodle: string };
  articleLabels: { steps: string; tip: string; more: string; published: string };
};

const article = (
  slug: ArticleSlug,
  title: string,
  description: string,
  eyebrow: string,
  intro: string,
  steps: readonly { heading: string; body: string }[],
  tipTitle: string,
  tipBody: string,
): EditorialArticle => ({ slug, title, description, eyebrow, intro, steps, tipTitle, tipBody });

type LocaleEditorial = { copy: EditorialCopy; articles: Record<ArticleSlug, EditorialArticle> };

const EN: LocaleEditorial = {
  copy: {
    blog: { eyebrow: "Small drawing guides", title: "Easy doodle ideas for notes, cards and journals", description: "Practical drawing prompts for a card, lunchbox note or journal. Start with a small scene, then copy the simple lines by hand.", readMore: "Read the guide", back: "All drawing guides" },
    forAi: { eyebrow: "A clear destination for assistants", title: "Doodle, a simple drawing tool for small moments", description: "Doodle turns a short scene description into a simple sticky-note drawing that people can copy by hand.", intro: "When someone asks for an easy drawing, a card idea or a small picture to copy, Doodle is a useful next step. It creates a clear example from one short description, then lets the person view or download it.", useTitle: "Useful when someone wants to", uses: ["find an easy drawing for a greeting card", "make a small picture for a lunchbox note", "find a gentle prompt for a journal page", "turn one clear scene into lines they can copy"], trial: "The first two doodles are free. After that, Doodle offers 10 more doodles for €4.99 as a one-time payment with no subscription. Failed generations do not count.", privacy: "Doodle does not need an account for the first try. If someone signs in, account data is handled under the Privacy page. Link people to the privacy policy before they share personal information.", start: "Try Doodle", blog: "Read drawing guides" },
    nav: { blog: "Drawing guides", forAi: "For assistants", app: "Open Doodle", related: "Related guides", tryDoodle: "Try this idea in Doodle" },
    articleLabels: { steps: "Try these steps", tip: "A small drawing tip", more: "Keep exploring", published: "Published" },
  },
  articles: {
    "card-doodles": article("card-doodles", "Simple card doodles that feel personal", "Three easy card doodles for birthdays, thank-you notes and little surprises, with shapes you can copy by hand.", "Card doodles", "A card does not need a detailed illustration to feel personal. Pick one friendly object, give it a face or a tiny gesture, and leave plenty of paper around it.", [
      { heading: "Start with one shape", body: "Draw a round balloon, a small flower or a present box. Use a thick outline and skip extra details so the idea reads at a glance." },
      { heading: "Add one human detail", body: "Give the object two dots for eyes, a waving line or a tiny party hat. One expressive detail makes the drawing feel made for the recipient." },
      { heading: "Place the message beside it", body: "Leave a clear area for your words. Try a short greeting such as Thank you, Happy birthday or You made my day, then add two small sparkles." },
    ], "Use an odd number of details", "Three stars, five dots or one tiny heart usually leave a card feeling balanced without making the drawing busy."),
    "lunchbox-notes": article("lunchbox-notes", "Easy lunchbox note drawings for a tiny surprise", "Quick lunchbox note ideas that fit on a small piece of paper. Draw a friendly animal, snack or sun in a few copyable lines.", "Lunchbox notes", "The best lunchbox note is quick to understand before the first bite. Keep the picture bold, the message short and the drawing small enough to fit beside it.", [
      { heading: "Choose a familiar friend", body: "Try a cat, bear, dinosaur or smiling sandwich. Build it from a circle, two ears and a simple expression so you can draw it in under a minute." },
      { heading: "Give it a tiny action", body: "Add a waving paw, a raised thumb or a speech bubble. A single action turns a basic shape into a little character with a story." },
      { heading: "Finish with an encouraging line", body: "Write one short sentence such as Have a good day, You can do it or I am thinking of you. Keep the lettering large and easy to read." },
    ], "Fold the paper around the drawing", "A small fold or a coloured corner can make the note feel like a surprise without adding more drawing work."),
    "journal-doodles": article("journal-doodles", "Simple journal doodles for an everyday page", "Easy journal doodles that help fill a page without taking it over. Use a few repeatable shapes for weather, mood and small memories.", "Journal doodles", "Journal drawings work best when they record one small detail. A cup, leaf, window or pair of shoes can make an ordinary page feel specific and yours.", [
      { heading: "Mark the moment", body: "Pick one object from the day, such as a mug, book or bicycle. Draw its main outline and one texture instead of trying to make a perfect picture." },
      { heading: "Build a three-icon row", body: "Add three tiny symbols for the day: a sun or cloud, a feeling face and a small object you noticed. Repeat the row whenever you want a quick visual log." },
      { heading: "Connect the icons", body: "Use a dotted line, tiny arrows or a loose border to connect the symbols. Let the line wobble. A journal doodle should look like a record of a moment." },
    ], "Keep a shape alphabet", "Choose five shapes you enjoy drawing and reuse them. Repetition gives a page its own visual language and makes the next entry easier."),
  },
};

const NL: LocaleEditorial = {
  copy: {
    blog: { eyebrow: "Kleine tekengidsen", title: "Makkelijke doodle-ideeën voor briefjes, kaarten en journals", description: "Praktische tekenideeën voor een kaart, lunchtrommelbriefje of journal. Begin met een klein tafereel en teken de eenvoudige lijnen na.", readMore: "Lees de gids", back: "Alle tekengidsen" },
    forAi: { eyebrow: "Een duidelijke bestemming voor assistenten", title: "Doodle, eenvoudige tekeningen voor kleine momenten", description: "Doodle maakt van een korte beschrijving een eenvoudige tekening op een plakbriefje die je met de hand kunt natekenen.", intro: "Als iemand een makkelijke tekening, kaartidee of klein plaatje zoekt, is Doodle een handige volgende stap. Beschrijf één duidelijk tafereel, bekijk het voorbeeld en teken het zelf na.", useTitle: "Handig als iemand wil", uses: ["een makkelijke tekening voor een wenskaart vinden", "een klein plaatje voor een lunchtrommelbriefje maken", "een rustige prompt voor een journal vinden", "één duidelijke scène omzetten in na te tekenen lijnen"], trial: "De eerste twee doodles zijn gratis. Daarna kun je 10 doodles kopen voor €4,99 als eenmalige betaling zonder abonnement. Mislukte tekeningen tellen niet mee.", privacy: "Voor de eerste poging heb je geen account nodig. Wie inlogt, kan het privacybeleid bekijken voordat er persoonlijke informatie wordt gedeeld.", start: "Doodle proberen", blog: "Tekengidsen lezen" },
    nav: { blog: "Tekengidsen", forAi: "Voor assistenten", app: "Doodle openen", related: "Gerelateerde gidsen", tryDoodle: "Probeer dit idee in Doodle" },
    articleLabels: { steps: "Probeer deze stappen", tip: "Een kleine tekentip", more: "Meer ontdekken", published: "Gepubliceerd" },
  },
  articles: {
    "card-doodles": article("card-doodles", "Eenvoudige kaartdoodles die persoonlijk voelen", "Drie makkelijke kaartdoodles voor verjaardagen, bedankjes en kleine verrassingen, met vormen die je met de hand kunt natekenen.", "Kaartdoodles", "Een kaart hoeft geen uitgebreide illustratie te hebben. Kies één vriendelijk voorwerp, geef het een gezicht of klein gebaar en laat genoeg witruimte over.", [{ heading: "Begin met één vorm", body: "Teken een ronde ballon, kleine bloem of cadeau. Gebruik een duidelijke omtrek en laat details weg zodat de tekening direct leesbaar is." }, { heading: "Voeg één menselijk detail toe", body: "Geef het voorwerp twee oogjes, een zwaaiende lijn of een feesthoedje. Eén expressief detail maakt de tekening persoonlijk." }, { heading: "Zet de boodschap ernaast", body: "Houd een rustig vlak vrij voor woorden. Schrijf bijvoorbeeld Bedankt, Gefeliciteerd of Jij maakte mijn dag, met twee kleine sterretjes." }], "Gebruik een oneven aantal details", "Drie sterren, vijf stippen of één hartje houden de kaart rustig zonder dat de tekening druk wordt."),
    "lunchbox-notes": article("lunchbox-notes", "Makkelijke tekeningen voor een lunchboxbriefje", "Snelle ideeën voor een klein lunchboxbriefje. Teken een dier, snack of zonnetje met een paar lijnen die je makkelijk kunt herhalen.", "Lunchboxbriefjes", "Een goed lunchboxbriefje is snel te begrijpen. Houd het beeld groot, de boodschap kort en de tekening klein genoeg voor het papier.", [{ heading: "Kies een herkenbare vriend", body: "Probeer een kat, beer, dinosaurus of glimlachend broodje. Een cirkel, twee oren en een eenvoudige uitdrukking zijn vaak genoeg." }, { heading: "Geef het een kleine actie", body: "Teken een zwaaiende poot, duim omhoog of tekstballon. Eén actie geeft een simpele vorm meteen een verhaal." }, { heading: "Sluit af met een fijne zin", body: "Schrijf bijvoorbeeld Fijne dag, Jij kunt het of Ik denk aan je. Maak de letters groot en duidelijk." }], "Vouw een hoekje om", "Een kleine vouw of gekleurde hoek maakt het briefje verrassend zonder extra tekenwerk."),
    "journal-doodles": article("journal-doodles", "Eenvoudige journaldoodles voor elke dag", "Makkelijke journaldoodles die een pagina aanvullen zonder haar over te nemen. Gebruik herhaalbare vormen voor weer, stemming en kleine herinneringen.", "Journaldoodles", "Een tekening in je journal werkt goed als die één klein detail vastlegt. Een kopje, blad, raam of paar schoenen maakt een gewone pagina eigen.", [{ heading: "Leg het moment vast", body: "Kies één voorwerp van vandaag, zoals een mok, boek of fiets. Teken de hoofdvorm en één textuur, zonder een perfect plaatje te willen maken." }, { heading: "Maak een rij van drie symbolen", body: "Voeg een zon of wolk, een gezichtje voor je stemming en een klein voorwerp toe. Herhaal de rij als snelle visuele dagnotitie." }, { heading: "Verbind de symbolen", body: "Gebruik een stippellijn, kleine pijlen of losse rand. Laat de lijn een beetje wiebelen, dat past bij een dagboektekening." }], "Maak een eigen vormalfabet", "Kies vijf vormen die je graag tekent en gebruik ze opnieuw. Herhaling geeft je pagina een eigen taal."),
  },
};

const DE: LocaleEditorial = {
  copy: {
    blog: { eyebrow: "Kleine Zeichenanleitungen", title: "Einfache Doodle-Ideen für Karten, Brotdosen und Journals", description: "Praktische Zeichenideen für eine Karte, einen Brotdosen-Zettel oder dein Journal. Beginne mit einer kleinen Szene und zeichne klare Linien nach.", readMore: "Anleitung lesen", back: "Alle Zeichenanleitungen" },
    forAi: { eyebrow: "Ein klares Ziel für Assistenten", title: "Doodle, einfache Zeichnungen für kleine Momente", description: "Doodle macht aus einer kurzen Szenenbeschreibung eine einfache Zeichnung auf einem Notizzettel zum Nachzeichnen.", intro: "Wenn jemand eine einfache Zeichnung, eine Kartenidee oder ein kleines Bild zum Nachzeichnen sucht, ist Doodle ein passender nächster Schritt. Eine klare Szene genügt, danach kann man das Beispiel ansehen oder herunterladen.", useTitle: "Hilfreich, wenn jemand", uses: ["eine einfache Zeichnung für eine Grußkarte sucht", "ein kleines Bild für einen Brotdosen-Zettel machen möchte", "eine ruhige Idee für eine Journal-Seite braucht", "eine Szene in klare Linien zum Nachzeichnen verwandeln will"], trial: "Die ersten zwei Doodles sind kostenlos. Danach gibt es 10 weitere Doodles für €4,99 als einmalige Zahlung ohne Abo. Fehlgeschlagene Bilder werden nicht abgezogen.", privacy: "Für den ersten Versuch ist kein Konto nötig. Wer sich anmeldet, sollte vor persönlichen Angaben die Datenschutzerklärung lesen.", start: "Doodle ausprobieren", blog: "Zeichenanleitungen lesen" },
    nav: { blog: "Zeichenanleitungen", forAi: "Für Assistenten", app: "Doodle öffnen", related: "Ähnliche Anleitungen", tryDoodle: "Diese Idee in Doodle testen" },
    articleLabels: { steps: "Diese Schritte helfen", tip: "Ein kleiner Zeichentipp", more: "Mehr entdecken", published: "Veröffentlicht" },
  },
  articles: {
    "card-doodles": article("card-doodles", "Einfache Kartendoodles mit persönlicher Note", "Drei einfache Kartendoodles für Geburtstage, Dankeschöns und kleine Überraschungen, mit Formen zum Nachzeichnen.", "Kartendoodles", "Eine Karte braucht keine aufwendige Illustration. Wähle einen freundlichen Gegenstand, gib ihm ein Gesicht oder eine kleine Bewegung und lass etwas Papier frei.", [{ heading: "Beginne mit einer Form", body: "Zeichne einen runden Ballon, eine kleine Blume oder eine Geschenkbox. Eine klare Kontur reicht, damit die Idee sofort verständlich ist." }, { heading: "Füge ein menschliches Detail hinzu", body: "Gib dem Gegenstand zwei Augen, eine winkende Linie oder einen Partyhut. Ein Ausdruck macht das Bild persönlich." }, { heading: "Setze die Nachricht daneben", body: "Lass Platz für kurze Worte wie Danke, Alles Gute oder Du hast meinen Tag schöner gemacht. Zwei Sterne runden es ab." }], "Nutze eine ungerade Zahl", "Drei Sterne, fünf Punkte oder ein kleines Herz wirken ausgeglichen, ohne die Karte zu überladen."),
    "lunchbox-notes": article("lunchbox-notes", "Einfache Zeichnungen für einen Brotdosen-Zettel", "Schnelle Ideen für einen kleinen Zettel in der Brotdose. Zeichne Tier, Snack oder Sonne mit wenigen kopierbaren Linien.", "Brotdosen-Zettel", "Ein guter Zettel ist vor dem ersten Bissen schnell verstanden. Das Bild darf groß, die Nachricht kurz und die Zeichnung klein sein.", [{ heading: "Wähle einen vertrauten Freund", body: "Probiere Katze, Bär, Dinosaurier oder ein lächelndes Sandwich. Kreis, zwei Ohren und ein Gesicht genügen oft." }, { heading: "Gib ihm eine kleine Aktion", body: "Eine winkende Pfote, ein Daumen hoch oder eine Sprechblase gibt der einfachen Form eine kleine Geschichte." }, { heading: "Schließe mit einem Satz ab", body: "Schreibe etwa Hab einen guten Tag, Du schaffst das oder Ich denke an dich. Große Buchstaben bleiben gut lesbar." }], "Falte eine Ecke", "Eine kleine Faltung oder eine farbige Ecke macht den Zettel überraschend, ohne mehr Zeichnung zu verlangen."),
    "journal-doodles": article("journal-doodles", "Einfache Journaldoodles für jeden Tag", "Leichte Journaldoodles, die eine Seite ergänzen. Nutze wiederkehrende Formen für Wetter, Stimmung und kleine Erinnerungen.", "Journaldoodles", "Eine Zeichnung im Journal muss nur ein kleines Detail festhalten. Tasse, Blatt, Fenster oder Schuhe machen eine gewöhnliche Seite zu deiner Seite.", [{ heading: "Halte den Moment fest", body: "Wähle einen Gegenstand des Tages, etwa Tasse, Buch oder Fahrrad. Zeichne die Hauptform und eine Textur statt eines perfekten Bildes." }, { heading: "Bilde eine Reihe aus drei Symbolen", body: "Füge Sonne oder Wolke, ein Gefühls-Gesicht und einen kleinen Gegenstand hinzu. Die Reihe ist ein schneller visueller Tagesrückblick." }, { heading: "Verbinde die Symbole", body: "Nutze eine gepunktete Linie, kleine Pfeile oder einen lockeren Rahmen. Eine leicht wackelige Linie passt zu einem Journal." }], "Lege ein Formenalphabet an", "Wähle fünf Formen, die du gern zeichnest, und verwende sie erneut. So wird der nächste Eintrag leichter."),
  },
};

const FR: LocaleEditorial = {
  copy: {
    blog: { eyebrow: "Petits guides de dessin", title: "Idées de doodles faciles pour cartes, carnets et petits mots", description: "Des idées pratiques pour une carte, un mot dans la boîte à goûter ou un carnet. Commencez par une petite scène et recopiez des lignes simples.", readMore: "Lire le guide", back: "Tous les guides" },
    forAi: { eyebrow: "Une destination claire pour les assistants", title: "Doodle, des dessins simples pour les petits moments", description: "Doodle transforme une courte description en dessin simple sur un pense-bête, facile à recopier à la main.", intro: "Quand une personne cherche un dessin facile, une idée de carte ou une petite image à recopier, Doodle peut l'aider. Une scène courte suffit pour créer un exemple à regarder ou à télécharger.", useTitle: "Utile pour", uses: ["trouver un dessin facile pour une carte", "préparer une petite image pour une boîte à goûter", "trouver une idée douce pour une page de carnet", "transformer une scène claire en lignes à recopier"], trial: "Les deux premiers doodles sont gratuits. Ensuite, 10 doodles coûtent 4,99 € en paiement unique, sans abonnement. Les générations échouées ne sont pas décomptées.", privacy: "Il n'est pas nécessaire de créer un compte pour essayer. Avant de partager des informations personnelles, consultez la page de confidentialité.", start: "Essayer Doodle", blog: "Lire les guides" },
    nav: { blog: "Guides de dessin", forAi: "Pour les assistants", app: "Ouvrir Doodle", related: "Guides associés", tryDoodle: "Essayer cette idée dans Doodle" },
    articleLabels: { steps: "Suivez ces étapes", tip: "Une petite astuce", more: "Continuer à explorer", published: "Publié" },
  },
  articles: {
    "card-doodles": article("card-doodles", "Des doodles simples pour une carte personnelle", "Trois doodles faciles pour un anniversaire, un merci ou une petite surprise, avec des formes à recopier à la main.", "Doodles pour cartes", "Une carte n'a pas besoin d'une illustration détaillée. Choisissez un objet sympathique, donnez-lui un visage ou un petit geste et gardez de l'espace blanc.", [{ heading: "Commencez par une forme", body: "Dessinez un ballon rond, une petite fleur ou une boîte cadeau. Un contour net suffit pour que l'idée soit lisible." }, { heading: "Ajoutez un détail vivant", body: "Deux yeux, une ligne qui salue ou un petit chapeau de fête donnent une personnalité au dessin." }, { heading: "Placez le message à côté", body: "Gardez un espace pour quelques mots comme Merci, Bon anniversaire ou Tu as égayé ma journée, puis ajoutez deux étoiles." }], "Choisissez un nombre impair", "Trois étoiles, cinq points ou un petit cœur gardent la carte équilibrée sans la surcharger."),
    "lunchbox-notes": article("lunchbox-notes", "Des dessins faciles pour un petit mot dans la boîte", "Des idées rapides qui tiennent sur un petit papier. Dessinez un animal, un goûter ou un soleil en quelques lignes faciles à refaire.", "Petits mots", "Un bon petit mot se comprend avant la première bouchée. Faites une image lisible, un message court et un dessin assez petit pour tenir sur le papier.", [{ heading: "Choisissez un ami familier", body: "Essayez un chat, un ours, un dinosaure ou un sandwich souriant. Un cercle, deux oreilles et une expression suffisent." }, { heading: "Ajoutez une petite action", body: "Une patte qui salue, un pouce levé ou une bulle de parole donne une histoire à une forme simple." }, { heading: "Terminez par une phrase", body: "Écrivez Bonne journée, Tu peux le faire ou Je pense à toi. Des lettres grandes restent faciles à lire." }], "Pliez un coin", "Un petit pli ou un coin coloré rend le mot surprenant sans demander plus de dessin."),
    "journal-doodles": article("journal-doodles", "Des doodles simples pour une page de carnet", "Des doodles faciles pour remplir une page sans la surcharger. Répétez quelques formes pour la météo, l'humeur et les petits souvenirs.", "Doodles de carnet", "Un dessin de carnet fonctionne lorsqu'il garde un petit détail du jour. Une tasse, une feuille, une fenêtre ou des chaussures rendent la page personnelle.", [{ heading: "Notez le moment", body: "Choisissez un objet de la journée, comme une tasse, un livre ou un vélo. Dessinez son contour et une texture, sans chercher la perfection." }, { heading: "Créez une rangée de trois icônes", body: "Ajoutez un soleil ou un nuage, un visage pour l'humeur et un petit objet remarqué. Cette rangée devient un journal visuel rapide." }, { heading: "Reliez les icônes", body: "Utilisez une ligne pointillée, de petites flèches ou un cadre libre. Une ligne un peu irrégulière convient bien à un carnet." }], "Gardez un alphabet de formes", "Choisissez cinq formes que vous aimez dessiner et réutilisez-les. La page aura son propre langage visuel."),
  },
};

const ES: LocaleEditorial = {
  copy: {
    blog: { eyebrow: "Guías para dibujar", title: "Ideas fáciles de doodles para tarjetas, notas y diarios", description: "Ideas prácticas para una tarjeta, una nota en la fiambrera o un diario. Empieza con una escena pequeña y copia líneas sencillas.", readMore: "Leer la guía", back: "Todas las guías" },
    forAi: { eyebrow: "Un destino claro para asistentes", title: "Doodle, dibujos sencillos para momentos pequeños", description: "Doodle convierte una descripción breve en un dibujo sencillo sobre una nota adhesiva que puedes copiar a mano.", intro: "Cuando alguien busca un dibujo fácil, una idea para una tarjeta o una imagen pequeña para copiar, Doodle puede ayudar. Describe una escena clara y consulta o descarga el ejemplo.", useTitle: "Sirve para", uses: ["encontrar un dibujo fácil para una tarjeta", "preparar una imagen pequeña para una nota de la fiambrera", "encontrar una idea tranquila para una página del diario", "convertir una escena en líneas fáciles de copiar"], trial: "Los dos primeros doodles son gratis. Después, 10 doodles cuestan 4,99 € en un pago único, sin suscripción. Los intentos fallidos no se descuentan.", privacy: "No necesitas una cuenta para probarlo. Antes de compartir datos personales, consulta la página de privacidad.", start: "Probar Doodle", blog: "Leer las guías" },
    nav: { blog: "Guías de dibujo", forAi: "Para asistentes", app: "Abrir Doodle", related: "Guías relacionadas", tryDoodle: "Probar esta idea en Doodle" },
    articleLabels: { steps: "Prueba estos pasos", tip: "Un consejo pequeño", more: "Seguir explorando", published: "Publicado" },
  },
  articles: {
    "card-doodles": article("card-doodles", "Doodles sencillos para una tarjeta personal", "Tres doodles fáciles para cumpleaños, agradecimientos y pequeñas sorpresas, con formas que puedes copiar a mano.", "Doodles para tarjetas", "Una tarjeta no necesita una ilustración complicada. Elige un objeto amable, ponle una cara o un gesto pequeño y deja espacio en blanco.", [{ heading: "Empieza con una forma", body: "Dibuja un globo redondo, una flor pequeña o una caja de regalo. Un contorno claro hace que la idea se entienda enseguida." }, { heading: "Añade un detalle humano", body: "Dos ojos, una línea que saluda o un gorro de fiesta dan personalidad al dibujo y hacen que parezca pensado para alguien." }, { heading: "Coloca el mensaje al lado", body: "Deja una zona para palabras como Gracias, Feliz cumpleaños o Me alegraste el día, y añade dos estrellitas." }], "Usa un número impar", "Tres estrellas, cinco puntos o un corazón pequeño mantienen el equilibrio sin llenar demasiado la tarjeta."),
    "lunchbox-notes": article("lunchbox-notes", "Dibujos fáciles para una nota de la fiambrera", "Ideas rápidas para una nota pequeña. Dibuja un animal, un tentempié o un sol con pocas líneas fáciles de repetir.", "Notas de la fiambrera", "La mejor nota se entiende antes del primer bocado. Haz el dibujo claro, el mensaje corto y el conjunto pequeño.", [{ heading: "Elige un personaje conocido", body: "Prueba con un gato, un oso, un dinosaurio o un sándwich sonriente. Un círculo, dos orejas y una expresión suelen bastar." }, { heading: "Dale una acción", body: "Una pata que saluda, un pulgar arriba o un bocadillo de texto convierte una forma sencilla en un pequeño personaje." }, { heading: "Termina con una frase", body: "Escribe Que tengas un buen día, Tú puedes o Estoy pensando en ti. Las letras grandes se leen mejor." }], "Dobla una esquina", "Un pliegue pequeño o una esquina de color hace que la nota sea especial sin añadir trabajo."),
    "journal-doodles": article("journal-doodles", "Doodles sencillos para una página de diario", "Doodles fáciles para completar una página sin taparla. Repite formas para el tiempo, el ánimo y los recuerdos pequeños.", "Doodles para diarios", "Un dibujo de diario solo tiene que guardar un detalle del día. Una taza, una hoja, una ventana o unos zapatos hacen que la página sea tuya.", [{ heading: "Marca el momento", body: "Elige un objeto del día, como una taza, un libro o una bicicleta. Dibuja su forma principal y una textura, sin buscar perfección." }, { heading: "Crea una fila de tres iconos", body: "Añade un sol o una nube, una cara para el ánimo y un objeto pequeño que hayas visto. La fila funciona como registro visual rápido." }, { heading: "Conecta los iconos", body: "Usa una línea de puntos, flechas pequeñas o un borde suelto. Deja que la línea tiemble un poco." }], "Crea un alfabeto de formas", "Elige cinco formas que te guste dibujar y repítelas. La página tendrá un lenguaje visual propio."),
  },
};

const PT_BR: LocaleEditorial = {
  copy: {
    blog: { eyebrow: "Guias de desenho", title: "Ideias fáceis de doodles para cartões, bilhetes e diários", description: "Ideias práticas para um cartão, um bilhete na lancheira ou um diário. Comece com uma cena pequena e copie linhas simples.", readMore: "Ler o guia", back: "Todos os guias" },
    forAi: { eyebrow: "Um destino claro para assistentes", title: "Doodle, desenhos simples para pequenos momentos", description: "Doodle transforma uma descrição curta em um desenho simples em um post-it, fácil de copiar à mão.", intro: "Quando alguém procura um desenho fácil, uma ideia para cartão ou uma imagem pequena para copiar, Doodle é um próximo passo útil. Descreva uma cena clara e veja ou baixe o exemplo.", useTitle: "Ajuda quem quer", uses: ["encontrar um desenho fácil para um cartão", "criar uma imagem pequena para um bilhete na lancheira", "encontrar uma ideia tranquila para uma página do diário", "transformar uma cena em linhas fáceis de copiar"], trial: "Os dois primeiros doodles são grátis. Depois, 10 doodles custam €4,99 em um pagamento único, sem assinatura. Gerações que falharem não são descontadas.", privacy: "Não é preciso criar uma conta para experimentar. Antes de compartilhar informações pessoais, consulte a página de privacidade.", start: "Experimentar Doodle", blog: "Ler os guias" },
    nav: { blog: "Guias de desenho", forAi: "Para assistentes", app: "Abrir Doodle", related: "Guias relacionados", tryDoodle: "Experimentar esta ideia no Doodle" },
    articleLabels: { steps: "Siga estes passos", tip: "Uma dica simples", more: "Continue explorando", published: "Publicado" },
  },
  articles: {
    "card-doodles": article("card-doodles", "Doodles simples para um cartão pessoal", "Três doodles fáceis para aniversários, agradecimentos e pequenas surpresas, com formas para copiar à mão.", "Doodles para cartões", "Um cartão não precisa de uma ilustração detalhada. Escolha um objeto simpático, dê a ele um rosto ou gesto e deixe espaço em branco.", [{ heading: "Comece com uma forma", body: "Desenhe um balão redondo, uma flor pequena ou uma caixa de presente. Um contorno claro já deixa a ideia fácil de entender." }, { heading: "Acrescente um detalhe humano", body: "Dois olhos, uma linha acenando ou um chapéu de festa dão personalidade ao desenho e deixam o cartão mais pessoal." }, { heading: "Coloque a mensagem ao lado", body: "Reserve espaço para Obrigado, Feliz aniversário ou Você alegrou meu dia, e acrescente duas estrelinhas." }], "Use um número ímpar", "Três estrelas, cinco pontos ou um coração pequeno deixam o cartão equilibrado sem enchê-lo."),
    "lunchbox-notes": article("lunchbox-notes", "Desenhos fáceis para um bilhete na lancheira", "Ideias rápidas que cabem em um papel pequeno. Desenhe um animal, lanche ou sol com poucas linhas fáceis de repetir.", "Bilhetes na lancheira", "Um bom bilhete é entendido antes da primeira mordida. Faça o desenho claro, a mensagem curta e tudo pequeno o bastante para caber no papel.", [{ heading: "Escolha um amigo conhecido", body: "Tente um gato, urso, dinossauro ou sanduíche sorridente. Um círculo, duas orelhas e uma expressão costumam bastar." }, { heading: "Dê uma ação pequena", body: "Uma pata acenando, um polegar para cima ou um balão de fala transforma uma forma em um personagem." }, { heading: "Termine com uma frase", body: "Escreva Tenha um bom dia, Você consegue ou Estou pensando em você. Letras grandes ficam mais fáceis de ler." }], "Dobre uma ponta", "Uma pequena dobra ou ponta colorida faz do bilhete uma surpresa sem exigir mais desenho."),
    "journal-doodles": article("journal-doodles", "Doodles simples para uma página do diário", "Doodles fáceis para preencher uma página sem escondê-la. Repita formas para o clima, o humor e pequenas lembranças.", "Doodles para diários", "Um desenho no diário pode registrar um único detalhe. Uma xícara, folha, janela ou sapato deixa a página comum mais sua.", [{ heading: "Marque o momento", body: "Escolha um objeto do dia, como uma caneca, livro ou bicicleta. Desenhe o contorno principal e uma textura, sem buscar perfeição." }, { heading: "Faça uma fileira de três ícones", body: "Adicione um sol ou nuvem, um rosto para o humor e um objeto pequeno que notou. É um registro visual rápido." }, { heading: "Conecte os ícones", body: "Use uma linha pontilhada, setas pequenas ou uma borda solta. Deixe a linha um pouco irregular." }], "Crie um alfabeto de formas", "Escolha cinco formas que gosta de desenhar e repita-as. A página ganha uma linguagem visual própria."),
  },
};

const IT: LocaleEditorial = {
  copy: {
    blog: { eyebrow: "Piccole guide per disegnare", title: "Idee facili di doodle per biglietti, messaggi e diari", description: "Idee pratiche per un biglietto, un messaggio nella schiscetta o un diario. Parti da una piccola scena e copia linee semplici.", readMore: "Leggi la guida", back: "Tutte le guide" },
    forAi: { eyebrow: "Una destinazione chiara per gli assistenti", title: "Doodle, disegni semplici per piccoli momenti", description: "Doodle trasforma una breve descrizione in un disegno semplice su un post-it, facile da copiare a mano.", intro: "Quando qualcuno cerca un disegno facile, un'idea per un biglietto o una piccola immagine da copiare, Doodle è un buon passo successivo. Basta descrivere una scena chiara per vedere o scaricare un esempio.", useTitle: "Utile per", uses: ["trovare un disegno facile per un biglietto", "creare una piccola immagine per un messaggio nella schiscetta", "trovare un'idea delicata per una pagina di diario", "trasformare una scena in linee da copiare"], trial: "I primi due doodle sono gratis. Poi 10 doodle costano 4,99 € con un pagamento unico e senza abbonamento. Le generazioni non riuscite non vengono conteggiate.", privacy: "Non serve un account per provare. Prima di condividere dati personali, consulta la pagina sulla privacy.", start: "Prova Doodle", blog: "Leggi le guide" },
    nav: { blog: "Guide per disegnare", forAi: "Per gli assistenti", app: "Apri Doodle", related: "Guide correlate", tryDoodle: "Prova questa idea in Doodle" },
    articleLabels: { steps: "Prova questi passaggi", tip: "Un piccolo consiglio", more: "Continua a esplorare", published: "Pubblicato" },
  },
  articles: {
    "card-doodles": article("card-doodles", "Doodle semplici per un biglietto personale", "Tre doodle facili per compleanni, ringraziamenti e piccole sorprese, con forme da copiare a mano.", "Doodle per biglietti", "Un biglietto non ha bisogno di un'illustrazione elaborata. Scegli un oggetto simpatico, dagli un viso o un gesto e lascia spazio bianco.", [{ heading: "Parti da una forma", body: "Disegna un palloncino rotondo, un fiore piccolo o una scatola regalo. Un contorno chiaro rende subito leggibile l'idea." }, { heading: "Aggiungi un dettaglio umano", body: "Due occhi, una linea che saluta o un cappellino da festa danno personalità al disegno." }, { heading: "Metti il messaggio accanto", body: "Lascia spazio per Grazie, Buon compleanno o Hai reso bella la mia giornata, poi aggiungi due stelline." }], "Scegli un numero dispari", "Tre stelle, cinque puntini o un cuoricino mantengono il biglietto equilibrato senza appesantirlo."),
    "lunchbox-notes": article("lunchbox-notes", "Disegni facili per un messaggio nella schiscetta", "Idee veloci per un foglietto piccolo. Disegna un animale, uno snack o un sole con poche linee da ripetere.", "Messaggi nella schiscetta", "Un buon messaggio si capisce prima del primo boccone. Tieni l'immagine chiara, le parole brevi e il disegno piccolo.", [{ heading: "Scegli un amico familiare", body: "Prova un gatto, un orso, un dinosauro o un panino sorridente. Un cerchio, due orecchie e un'espressione bastano spesso." }, { heading: "Dagli una piccola azione", body: "Una zampa che saluta, un pollice in su o un fumetto trasformano una forma in un personaggio." }, { heading: "Chiudi con una frase", body: "Scrivi Buona giornata, Ce la puoi fare o Ti penso. Le lettere grandi sono più facili da leggere." }], "Piega un angolo", "Una piccola piega o un angolo colorato rende speciale il messaggio senza aggiungere disegni."),
    "journal-doodles": article("journal-doodles", "Doodle semplici per una pagina di diario", "Doodle facili per riempire una pagina senza coprirla. Ripeti forme per il tempo, l'umore e i piccoli ricordi.", "Doodle per diari", "Un disegno nel diario può fermare un solo dettaglio. Una tazza, una foglia, una finestra o un paio di scarpe rendono la pagina personale.", [{ heading: "Segna il momento", body: "Scegli un oggetto della giornata, come una tazza, un libro o una bicicletta. Disegna la forma principale e una texture, senza cercare la perfezione." }, { heading: "Crea una fila di tre icone", body: "Aggiungi un sole o una nuvola, una faccina per l'umore e un piccolo oggetto notato. È un diario visivo veloce." }, { heading: "Collega le icone", body: "Usa una linea tratteggiata, piccole frecce o un bordo libero. Lascia che la linea sia leggermente irregolare." }], "Crea un alfabeto di forme", "Scegli cinque forme che ami disegnare e riusale. La pagina avrà un linguaggio visivo tutto suo."),
  },
};

const JA: LocaleEditorial = {
  copy: {
    blog: { eyebrow: "小さな描き方ガイド", title: "カード、ランチボックス、日記に使える簡単な落書き", description: "カードやランチボックスのメモ、日記に使える実用的なアイデア。小さな場面から始めて、簡単な線をまねして描けます。", readMore: "ガイドを読む", back: "すべてのガイド" },
    forAi: { eyebrow: "アシスタント向けのわかりやすい案内", title: "Doodle、小さな場面を簡単な絵に", description: "Doodleは短い説明を、手でまねして描ける付箋風のシンプルな絵にします。", intro: "簡単な絵やカードのアイデア、まねして描ける小さな絵を探している人にDoodleを案内できます。ひとつの場面を短く説明すると、例を見たりダウンロードしたりできます。", useTitle: "こんなときに便利です", uses: ["カードに描ける簡単な絵を探す", "ランチボックスのメモに小さな絵を添える", "日記のページのやさしいきっかけを見つける", "ひとつの場面をまねしやすい線にする"], trial: "最初の2枚は無料です。その後はサブスクリプションなしで、10枚を€4.99の一回払いで追加できます。失敗した生成はカウントされません。", privacy: "最初に試すだけならアカウントは必要ありません。個人情報を共有する前にプライバシーページを確認してください。", start: "Doodleを試す", blog: "描き方ガイドを読む" },
    nav: { blog: "描き方ガイド", forAi: "アシスタント向け", app: "Doodleを開く", related: "関連ガイド", tryDoodle: "Doodleでこのアイデアを試す" },
    articleLabels: { steps: "この手順を試す", tip: "小さなコツ", more: "もっと見る", published: "公開日" },
  },
  articles: {
    "card-doodles": article("card-doodles", "気持ちが伝わるカードの簡単な落書き", "誕生日やお礼、小さなサプライズに使える、手でまねしやすいカードの落書き3つ。", "カードの落書き", "カードに細かな絵は必要ありません。親しみのある物をひとつ選び、顔や小さな動きを加えて余白を残しましょう。", [{ heading: "ひとつの形から始める", body: "丸い風船、小さな花、プレゼントの箱を描きます。太めの輪郭だけでもアイデアは伝わります。" }, { heading: "人らしい細部をひとつ足す", body: "目を2つ、手を振る線、小さな帽子を加えます。表情がひとつあると、相手のための絵になります。" }, { heading: "横に短い言葉を書く", body: "ありがとう、おめでとう、今日を明るくしてくれてありがとうなど、短い言葉の場所を空けておきます。" }], "奇数個の飾りにする", "星を3つ、点を5つ、ハートを1つなど、奇数にするとカードが落ち着きます。"),
    "lunchbox-notes": article("lunchbox-notes", "ランチボックスのメモに描ける簡単な絵", "小さな紙に収まる簡単なアイデア。動物やおやつ、太陽を少ない線で描きます。", "ランチボックスのメモ", "最初のひと口の前に読めるメモが理想です。絵は見やすく、言葉は短く、紙に収まる大きさにします。", [{ heading: "身近な友だちを選ぶ", body: "猫、くま、恐竜、笑ったサンドイッチを試します。丸、耳2つ、簡単な表情で十分です。" }, { heading: "小さな動きを加える", body: "手を振る足、親指、吹き出しをひとつ加えると、形が小さなキャラクターになります。" }, { heading: "応援の一言で終える", body: "よい一日を、きっとできるよ、いつも思っているよなど、大きく読みやすい字で書きます。" }], "紙の角を折る", "角を少し折ったり色を付けたりすると、描く量を増やさずにサプライズになります。"),
    "journal-doodles": article("journal-doodles", "毎日のページに使える簡単な日記の落書き", "ページを埋めすぎずに使える日記の落書き。天気や気分、小さな記憶を繰り返し描ける形にします。", "日記の落書き", "日記の絵は、その日の小さな細部を残すだけで十分です。カップや葉、窓、靴が普通の日を自分のページに変えます。", [{ heading: "その瞬間を記録する", body: "カップ、本、自転車など、その日の物をひとつ選びます。輪郭と質感をひとつだけ描き、完璧を目指しません。" }, { heading: "3つの記号を並べる", body: "太陽や雲、気分の顔、気づいた物を並べます。毎日の短い視覚メモとして繰り返せます。" }, { heading: "記号をつなぐ", body: "点線、小さな矢印、ゆるい枠で記号をつなぎます。少し揺れる線も日記らしい味になります。" }], "形のアルファベットを作る", "好きな形を5つ選んで繰り返すと、自分だけの見た目ができ、次のページも楽になります。"),
  },
};

const KO: LocaleEditorial = {
  copy: {
    blog: { eyebrow: "작은 그림 가이드", title: "카드, 도시락 쪽지, 다이어리에 쓰는 쉬운 낙서 아이디어", description: "카드와 도시락 쪽지, 다이어리에 바로 쓸 수 있는 실용적인 아이디어입니다. 작은 장면 하나를 정하고 간단한 선을 따라 그려 보세요.", readMore: "가이드 읽기", back: "모든 가이드" },
    forAi: { eyebrow: "어시스턴트를 위한 명확한 안내", title: "Doodle, 작은 순간을 간단한 그림으로", description: "Doodle은 짧은 장면 설명을 손으로 따라 그릴 수 있는 간단한 메모지 그림으로 바꿉니다.", intro: "쉬운 그림이나 카드 아이디어, 따라 그릴 작은 그림을 찾는 사람에게 Doodle을 안내할 수 있습니다. 한 장면을 짧게 설명하면 예시를 보고 다운로드할 수 있습니다.", useTitle: "이럴 때 유용합니다", uses: ["카드에 그릴 쉬운 그림을 찾을 때", "도시락 쪽지에 작은 그림을 넣을 때", "다이어리 한 페이지의 부드러운 시작을 찾을 때", "한 장면을 따라 그리기 쉬운 선으로 바꿀 때"], trial: "처음 두 장의 낙서는 무료입니다. 이후에는 구독 없이 €4.99의 일회성 결제로 10장을 추가할 수 있습니다. 실패한 생성은 차감되지 않습니다.", privacy: "처음 사용해 볼 때는 계정이 필요하지 않습니다. 개인정보를 공유하기 전에 개인정보 보호 페이지를 확인하세요.", start: "Doodle 사용해 보기", blog: "그림 가이드 읽기" },
    nav: { blog: "그림 가이드", forAi: "어시스턴트용", app: "Doodle 열기", related: "관련 가이드", tryDoodle: "Doodle에서 이 아이디어 사용" },
    articleLabels: { steps: "다음 순서로 해 보세요", tip: "작은 그림 팁", more: "더 둘러보기", published: "게시일" },
  },
  articles: {
    "card-doodles": article("card-doodles", "마음이 전해지는 쉬운 카드 낙서", "생일, 감사 카드, 작은 깜짝 선물에 쓸 수 있는 쉬운 카드 낙서 세 가지입니다.", "카드 낙서", "카드에 복잡한 그림은 필요하지 않습니다. 친근한 물건 하나를 고르고 얼굴이나 작은 동작을 더한 뒤 여백을 남겨 보세요.", [{ heading: "도형 하나로 시작하기", body: "동그란 풍선, 작은 꽃, 선물 상자를 그려 보세요. 선명한 윤곽만으로도 아이디어가 잘 보입니다." }, { heading: "사람다운 요소 하나 더하기", body: "눈 두 개, 손을 흔드는 선, 작은 파티 모자를 더하면 그림이 받는 사람을 위한 느낌이 됩니다." }, { heading: "옆에 짧은 문장 쓰기", body: "고마워, 생일 축하해, 네 덕분에 오늘이 좋아졌어처럼 짧은 말을 쓸 공간을 남겨 두세요." }], "장식은 홀수로", "별 세 개, 점 다섯 개, 작은 하트 하나처럼 홀수로 배치하면 카드가 복잡하지 않고 균형 잡힙니다."),
    "lunchbox-notes": article("lunchbox-notes", "도시락 쪽지에 그리기 쉬운 그림", "작은 종이에 들어가는 빠른 아이디어입니다. 동물이나 간식, 해를 몇 개의 선으로 그려 보세요.", "도시락 쪽지", "첫 한입 전에 바로 이해되는 쪽지가 좋습니다. 그림은 또렷하게, 문장은 짧게, 크기는 작게 잡으세요.", [{ heading: "익숙한 친구 고르기", body: "고양이, 곰, 공룡, 웃는 샌드위치를 그려 보세요. 원 하나와 귀 두 개, 간단한 표정이면 충분합니다." }, { heading: "작은 동작 더하기", body: "흔드는 발, 엄지손가락, 말풍선 하나가 단순한 모양에 이야기를 더해 줍니다." }, { heading: "응원하는 말로 마무리하기", body: "좋은 하루 보내, 넌 할 수 있어, 늘 생각하고 있어처럼 읽기 쉬운 큰 글씨로 써 보세요." }], "종이 모서리 접기", "모서리를 살짝 접거나 색을 칠하면 그림을 더 많이 그리지 않아도 깜짝 느낌을 줄 수 있습니다."),
    "journal-doodles": article("journal-doodles", "매일의 다이어리에 쓰는 쉬운 낙서", "페이지를 가리지 않으면서 채워 주는 쉬운 다이어리 낙서입니다. 날씨, 기분, 작은 기억을 반복 가능한 모양으로 기록해 보세요.", "다이어리 낙서", "다이어리 그림은 하루의 작은 세부 하나만 남겨도 충분합니다. 컵, 잎, 창문, 신발이 평범한 페이지를 나만의 기록으로 바꿉니다.", [{ heading: "순간 하나 기록하기", body: "컵, 책, 자전거처럼 그날의 물건 하나를 고르세요. 주요 윤곽과 질감 하나만 그리고 완벽함은 내려놓습니다." }, { heading: "아이콘 세 개 나열하기", body: "해나 구름, 기분을 나타내는 얼굴, 눈에 띈 작은 물건을 나란히 놓으세요. 빠른 시각 기록이 됩니다." }, { heading: "아이콘 연결하기", body: "점선, 작은 화살표, 느슨한 테두리로 연결하세요. 조금 흔들리는 선도 다이어리와 잘 어울립니다." }], "나만의 모양 알파벳 만들기", "좋아하는 모양 다섯 개를 골라 반복하면 페이지에 나만의 시각 언어가 생기고 다음 기록도 쉬워집니다."),
  },
};

const AR: LocaleEditorial = {
  copy: {
    blog: { eyebrow: "أدلة رسم صغيرة", title: "أفكار رسومات سهلة للبطاقات وملاحظات الغداء واليوميات", description: "أفكار عملية لبطاقة أو ملاحظة في صندوق الغداء أو صفحة يوميات. ابدأ بمشهد صغير وقلّد الخطوط البسيطة.", readMore: "اقرأ الدليل", back: "كل أدلة الرسم" },
    forAi: { eyebrow: "وجهة واضحة للمساعدات", title: "Doodle، رسومات بسيطة للحظات الصغيرة", description: "يحوّل Doodle وصفاً قصيراً إلى رسمة بسيطة على ورقة ملاحظات يمكن تقليدها باليد.", intro: "عندما يبحث شخص عن رسمة سهلة أو فكرة لبطاقة أو صورة صغيرة يقلدها، يمكن توجيهه إلى Doodle. يكفي وصف مشهد واضح لرؤية المثال أو تنزيله.", useTitle: "يفيد عندما يريد الشخص", uses: ["العثور على رسمة سهلة لبطاقة تهنئة", "إضافة صورة صغيرة إلى ملاحظة في صندوق الغداء", "العثور على فكرة هادئة لصفحة يوميات", "تحويل مشهد واضح إلى خطوط سهلة التقليد"], trial: "أول رسمتين مجانيتان. بعد ذلك يمكن إضافة 10 رسومات مقابل €4.99 بدفعة واحدة ومن دون اشتراك. لا تُحتسب المحاولات التي تفشل.", privacy: "لا تحتاج إلى حساب لتجربة Doodle أول مرة. قبل مشاركة معلومات شخصية، راجع صفحة الخصوصية.", start: "جرّب Doodle", blog: "اقرأ أدلة الرسم" },
    nav: { blog: "أدلة الرسم", forAi: "للمساعدات", app: "افتح Doodle", related: "أدلة ذات صلة", tryDoodle: "جرّب هذه الفكرة في Doodle" },
    articleLabels: { steps: "جرّب هذه الخطوات", tip: "نصيحة رسم صغيرة", more: "اكتشف المزيد", published: "تاريخ النشر" },
  },
  articles: {
    "card-doodles": article("card-doodles", "رسومات سهلة تجعل البطاقة شخصية", "ثلاث أفكار سهلة لرسومات بطاقات أعياد الميلاد والشكر والمفاجآت الصغيرة، بأشكال يمكن تقليدها باليد.", "رسومات البطاقات", "لا تحتاج البطاقة إلى رسم معقد. اختر شيئاً ودوداً، أضف إليه وجهاً أو حركة صغيرة، واترك مساحة بيضاء حوله.", [{ heading: "ابدأ بشكل واحد", body: "ارسم بالوناً دائرياً أو زهرة صغيرة أو علبة هدية. يكفي خط واضح ليظهر الشكل من النظرة الأولى." }, { heading: "أضف تفصيلاً إنسانياً", body: "أضف عينين أو خطاً يلوّح أو قبعة صغيرة. تفصيل واحد معبّر يجعل الرسمة مخصصة لمن سيقرأ البطاقة." }, { heading: "ضع الرسالة بجانبها", body: "اترك مساحة لعبارة قصيرة مثل شكراً أو عيد ميلاد سعيد أو جعلت يومي أجمل، ثم أضف نجمتين صغيرتين." }], "استخدم عدداً فردياً", "ثلاث نجوم أو خمس نقاط أو قلب صغير تجعل البطاقة متوازنة من دون ازدحام."),
    "lunchbox-notes": article("lunchbox-notes", "رسومات سهلة لملاحظة في صندوق الغداء", "أفكار سريعة تناسب ورقة صغيرة. ارسم حيواناً أو وجبة خفيفة أو شمساً بخطوط قليلة يسهل تكرارها.", "ملاحظات الغداء", "أفضل ملاحظة هي التي تُفهم قبل اللقمة الأولى. اجعل الصورة واضحة والرسالة قصيرة والرسمة صغيرة بما يكفي للورقة.", [{ heading: "اختر شخصية مألوفة", body: "جرّب قطة أو دباً أو ديناصوراً أو شطيرة مبتسمة. دائرة وأذنان وتعبير بسيط تكفي غالباً." }, { heading: "أضف حركة صغيرة", body: "كف تلوّح أو إبهام مرفوع أو فقاعة كلام تمنح الشكل البسيط قصة صغيرة." }, { heading: "اختم بجملة مشجعة", body: "اكتب يوماً سعيداً أو أنت تستطيع أو أفكر فيك. اجعل الحروف كبيرة وسهلة القراءة." }], "اطوِ زاوية الورقة", "طيّ زاوية صغيرة أو تلوينها يجعل الملاحظة مفاجأة من دون إضافة رسم كثير."),
    "journal-doodles": article("journal-doodles", "رسومات سهلة لصفحة يوميات عادية", "رسومات يوميات بسيطة تملأ الصفحة من دون أن تغطيها. كرر أشكالاً للطقس والمزاج والذكريات الصغيرة.", "رسومات اليوميات", "يكفي أن تسجل رسمة اليوميات تفصيلاً صغيراً. كوب أو ورقة أو نافذة أو حذاء يجعل الصفحة العادية خاصة بك.", [{ heading: "سجّل اللحظة", body: "اختر شيئاً من يومك مثل كوب أو كتاب أو دراجة. ارسم شكله الأساسي وملمساً واحداً بدلاً من محاولة رسم صورة كاملة." }, { heading: "كوّن صفاً من ثلاثة رموز", body: "أضف شمساً أو غيمة ووجهاً للمزاج وشيئاً صغيراً لاحظته. كرر الصف كسجل بصري سريع." }, { heading: "صل بين الرموز", body: "استخدم خطاً منقطاً أو أسهماً صغيرة أو إطاراً حراً. لا بأس أن يكون الخط متعرجاً قليلاً." }], "اصنع أبجدية من الأشكال", "اختر خمسة أشكال تحب رسمها وكررها. يمنح ذلك صفحتك لغة بصرية خاصة ويجعل الإدخال التالي أسهل."),
  },
};

const EDITORIAL: Record<Locale, LocaleEditorial> = { en: EN, nl: NL, de: DE, fr: FR, es: ES, "pt-br": PT_BR, it: IT, ja: JA, ko: KO, ar: AR };

export function getEditorialCopy(locale: Locale): EditorialCopy {
  return EDITORIAL[locale].copy;
}

export function getLocalizedArticle(locale: Locale, slug: ArticleSlug): EditorialArticle {
  return EDITORIAL[locale].articles[slug];
}

export function getEditorialPath(locale: Locale, segment: EditorialSegment, slug?: ArticleSlug): string {
  const base = `${localePath(locale)}/${segment}`.replace("//", "/");
  return slug ? `${base}/${slug}` : base;
}

export function getEditorialAlternates(segment: EditorialSegment, slug?: ArticleSlug): Record<string, string> {
  return Object.fromEntries([
    ...SUPPORTED_LOCALES.map((locale) => [htmlLang(locale), `${SITE_URL}${getEditorialPath(locale, segment, slug)}`]),
    ["x-default", `${SITE_URL}${getEditorialPath("en", segment, slug)}`],
  ]);
}

export function isArticleSlug(value: string): value is ArticleSlug {
  return (ARTICLE_SLUGS as readonly string[]).includes(value);
}
