export const SCENE_SUGGESTIONS_BY_LOCALE = {
  en: [
    "Two friends baking pancakes",
    "A sleepy astronaut resting on the moon",
    "A grandparent teaching a child to fish",
    "A cat in a raincoat sharing an umbrella with a tiny bird",
    "A dog offering a small flower to a cat",
    "Two siblings building a blanket fort",
    "A person warming both hands around a steaming mug",
    "A child running with a kite",
    "Two cats recreating an upside-down superhero kiss",
    "A tiny chef stirring a giant soup pot",
    "A bear reading a bedtime story to a rabbit",
    "A couple dancing in the kitchen",
    "A penguin carrying a birthday cake",
    "A parent tying a child's shoelace",
    "Two friends taking a silly selfie",
    "A cat watering three small flowers",
    "A dog sleeping under a desk",
    "A person giving someone a warm scarf",
    "Two children jumping in one puddle",
    "A rabbit painting a tiny picture",
    "A superhero making breakfast",
    "A person waving from a train window",
    "Two friends sharing one pair of headphones",
    "A cat reaching for a falling leaf",
    "A child hugging a large teddy bear",
    "A couple watching stars from a rooftop",
    "A dog waiting beside a picnic basket",
    "A person planting a small tree",
    "Two birds building a nest together",
    "A baker presenting one perfect cupcake",
    "A child helping a snail cross a path",
    "Two friends playing a board game",
    "A cat sleeping on an open book",
    "A person carrying groceries in the rain",
    "A tiny ghost drinking hot chocolate",
    "A dog wearing a party hat",
    "A child mailing a heart-shaped letter",
    "Two people high-fiving after finishing a puzzle",
    "A rabbit holding a lantern at night",
    "A person teaching a robot to dance",
    "A cat and dog sharing a sunny windowsill",
    "A child making a snow angel",
    "A little fox carrying a thank-you note",
    "A frog reading under a leaf",
    "A mouse sharing a cookie with a friend",
    "A sun tucking a star into bed",
    "A duck paddling beside a paper boat",
    "A child placing a sticker on a notebook",
    "A rabbit tying a ribbon around a gift",
    "A koala waving from a lunchbox",
  ],
  nl: [
    "Twee vrienden bakken pannenkoeken",
    "Een slaperige astronaut rust op de maan",
    "Een grootouder leert een kind vissen",
    "Een kat in een regenjas deelt een paraplu met een klein vogeltje",
    "Een hond geeft een kat een bloemetje",
    "Twee broers en zussen bouwen een dekentent",
    "Iemand warmt beide handen aan een dampende mok",
    "Een kind rent met een vlieger",
    "Twee katten doen een omgekeerde superhelden-kus na",
    "Een kleine kok roert in een enorme soeppan",
    "Een beer leest een verhaaltje voor het slapengaan aan een konijn",
    "Een stel danst in de keuken",
    "Een pinguïn draagt een verjaardagstaart",
    "Een ouder strikt de veters van een kind",
    "Twee vrienden maken een gekke selfie",
    "Een kat geeft drie kleine bloemen water",
    "Een hond slaapt onder een bureau",
    "Iemand geeft een ander een warme sjaal",
    "Twee kinderen springen in één plas",
    "Een konijn schildert een klein schilderijtje",
    "Een superheld maakt ontbijt",
    "Iemand zwaait vanuit een treinraam",
    "Twee vrienden delen één koptelefoon",
    "Een kat reikt naar een vallend blad",
    "Een kind knuffelt een grote teddybeer",
    "Een stel kijkt vanaf een dak naar de sterren",
    "Een hond wacht naast een picknickmand",
    "Iemand plant een kleine boom",
    "Twee vogels bouwen samen een nest",
    "Een bakker presenteert één perfecte cupcake",
    "Een kind helpt een slak een pad over",
    "Twee vrienden spelen een bordspel",
    "Een kat slaapt op een open boek",
    "Iemand draagt boodschappen in de regen",
    "Een klein spook drinkt warme chocolademelk",
    "Een hond met een feesthoedje",
    "Een kind doet een hartvormige brief op de post",
    "Twee mensen geven elkaar een high five nadat ze een puzzel af hebben",
    "Een konijn houdt 's nachts een lantaarn vast",
    "Iemand leert een robot dansen",
    "Een kat en hond delen een zonnige vensterbank",
    "Een kind maakt een sneeuwengel",
    "Een klein vosje draagt een bedankbriefje",
    "Een kikker leest onder een blad",
    "Een muis deelt een koekje met een vriend",
    "Een zon stopt een ster in bed",
    "Een eend peddelt naast een papieren bootje",
    "Een kind plakt een sticker in een notitieboek",
    "Een konijn knoopt een lint om een cadeau",
    "Een koala zwaait vanuit een lunchtrommel",
  ],
  de: [
    "Zwei Freunde backen Pfannkuchen",
    "Ein müder Astronaut ruht auf dem Mond",
    "Ein Großelternteil bringt einem Kind das Angeln bei",
    "Eine Katze im Regenmantel teilt einen Regenschirm mit einem kleinen Vogel",
    "Ein Hund schenkt einer Katze eine kleine Blume",
    "Zwei Geschwister bauen eine Deckenburg",
    "Eine Person wärmt beide Hände an einer dampfenden Tasse",
    "Ein Kind läuft mit einem Drachen",
    "Zwei Katzen stellen einen Kuss von Superhelden auf dem Kopf nach",
    "Ein kleiner Koch rührt in einem riesigen Suppentopf",
    "Ein Bär liest einem Kaninchen eine Gute-Nacht-Geschichte vor",
    "Ein Paar tanzt in der Küche",
    "Ein Pinguin trägt eine Geburtstagstorte",
    "Ein Elternteil bindet einem Kind die Schnürsenkel",
    "Zwei Freunde machen ein albernes Selfie",
    "Eine Katze gießt drei kleine Blumen",
    "Ein Hund schläft unter einem Schreibtisch",
    "Jemand schenkt einer Person einen warmen Schal",
    "Zwei Kinder springen in eine Pfütze",
    "Ein Kaninchen malt ein kleines Bild",
    "Ein Superheld macht Frühstück",
    "Jemand winkt aus einem Zugfenster",
    "Zwei Freunde teilen sich einen Kopfhörer",
    "Eine Katze greift nach einem fallenden Blatt",
    "Ein Kind umarmt einen großen Teddybären",
    "Ein Paar schaut von einem Dach aus die Sterne an",
    "Ein Hund wartet neben einem Picknickkorb",
    "Jemand pflanzt einen kleinen Baum",
    "Zwei Vögel bauen gemeinsam ein Nest",
    "Ein Bäcker präsentiert einen perfekten Cupcake",
    "Ein Kind hilft einer Schnecke über einen Weg",
    "Zwei Freunde spielen ein Brettspiel",
    "Eine Katze schläft auf einem offenen Buch",
    "Jemand trägt bei Regen Einkäufe",
    "Ein kleiner Geist trinkt heiße Schokolade",
    "Ein Hund mit Partyhut",
    "Ein Kind wirft einen herzförmigen Brief ein",
    "Zwei Menschen geben sich nach einem fertigen Puzzle ein High Five",
    "Ein Kaninchen hält nachts eine Laterne",
    "Jemand bringt einem Roboter das Tanzen bei",
    "Eine Katze und ein Hund teilen sich eine sonnige Fensterbank",
    "Ein Kind macht einen Schneeengel",
    "Ein kleiner Fuchs trägt einen Dankeszettel",
    "Ein Frosch liest unter einem Blatt",
    "Eine Maus teilt einen Keks mit einem Freund",
    "Eine Sonne bringt einen Stern ins Bett",
    "Eine Ente paddelt neben einem Papierboot",
    "Ein Kind klebt einen Sticker in ein Notizbuch",
    "Ein Kaninchen bindet ein Band um ein Geschenk",
    "Ein Koala winkt aus einer Brotdose",
  ],
  fr: [
    "Deux amis font des crêpes",
    "Un astronaute fatigué se repose sur la lune",
    "Un grand-parent apprend à un enfant à pêcher",
    "Un chat en imperméable partage un parapluie avec un petit oiseau",
    "Un chien offre une petite fleur à un chat",
    "Deux frères et sœurs construisent une cabane avec des couvertures",
    "Une personne réchauffe ses deux mains autour d’une tasse fumante",
    "Un enfant court avec un cerf-volant",
    "Deux chats rejouent un baiser de super-héros à l’envers",
    "Un petit chef remue une énorme marmite de soupe",
    "Un ours lit une histoire du soir à un lapin",
    "Un couple danse dans la cuisine",
    "Un pingouin porte un gâteau d’anniversaire",
    "Un parent attache les lacets d’un enfant",
    "Deux amis prennent un selfie amusant",
    "Un chat arrose trois petites fleurs",
    "Un chien dort sous un bureau",
    "Une personne offre une écharpe chaude à quelqu’un",
    "Deux enfants sautent dans une flaque",
    "Un lapin peint un tout petit tableau",
    "Un super-héros prépare le petit-déjeuner",
    "Une personne fait signe depuis la fenêtre d’un train",
    "Deux amis partagent une paire d’écouteurs",
    "Un chat attrape une feuille qui tombe",
    "Un enfant serre un gros ours en peluche dans ses bras",
    "Un couple regarde les étoiles depuis un toit",
    "Un chien attend près d’un panier de pique-nique",
    "Une personne plante un petit arbre",
    "Deux oiseaux construisent un nid ensemble",
    "Un pâtissier présente un cupcake parfait",
    "Un enfant aide un escargot à traverser un chemin",
    "Deux amis jouent à un jeu de société",
    "Un chat dort sur un livre ouvert",
    "Une personne porte des courses sous la pluie",
    "Un petit fantôme boit un chocolat chaud",
    "Un chien porte un chapeau de fête",
    "Un enfant poste une lettre en forme de cœur",
    "Deux personnes se tapent dans la main après avoir fini un puzzle",
    "Un lapin tient une lanterne dans la nuit",
    "Une personne apprend à un robot à danser",
    "Un chat et un chien partagent un rebord de fenêtre ensoleillé",
    "Un enfant fait un ange dans la neige",
    "Un petit renard porte un mot de remerciement",
    "Une grenouille lit sous une feuille",
    "Une souris partage un biscuit avec un ami",
    "Un soleil borde une étoile dans son lit",
    "Un canard pagaye près d’un bateau en papier",
    "Un enfant colle un autocollant dans un carnet",
    "Un lapin noue un ruban autour d’un cadeau",
    "Un koala fait coucou depuis une boîte à goûter",
  ],
  es: [
    "Dos amigos haciendo tortitas",
    "Un astronauta soñoliento descansando en la luna",
    "Un abuelo enseñando a pescar a un niño",
    "Un gato con impermeable compartiendo un paraguas con un pajarito",
    "Un perro ofreciéndole una flor pequeña a un gato",
    "Dos hermanos construyendo un fuerte con mantas",
    "Una persona calentándose las dos manos con una taza humeante",
    "Un niño corriendo con una cometa",
    "Dos gatos imitando un beso de superhéroe al revés",
    "Un pequeño chef removiendo una olla enorme de sopa",
    "Un oso leyendo un cuento de buenas noches a un conejo",
    "Una pareja bailando en la cocina",
    "Un pingüino llevando una tarta de cumpleaños",
    "Un padre atando los cordones de un niño",
    "Dos amigos haciéndose un selfie divertido",
    "Un gato regando tres flores pequeñas",
    "Un perro durmiendo debajo de un escritorio",
    "Una persona regalándole una bufanda cálida a alguien",
    "Dos niños saltando en un charco",
    "Un conejo pintando un cuadro diminuto",
    "Un superhéroe preparando el desayuno",
    "Una persona saludando desde la ventana de un tren",
    "Dos amigos compartiendo unos auriculares",
    "Un gato intentando alcanzar una hoja que cae",
    "Un niño abrazando un oso de peluche grande",
    "Una pareja mirando las estrellas desde una azotea",
    "Un perro esperando junto a una cesta de picnic",
    "Una persona plantando un árbol pequeño",
    "Dos pájaros construyendo un nido juntos",
    "Un pastelero presentando un cupcake perfecto",
    "Un niño ayudando a un caracol a cruzar un camino",
    "Dos amigos jugando a un juego de mesa",
    "Un gato durmiendo sobre un libro abierto",
    "Una persona llevando la compra bajo la lluvia",
    "Un fantasmita bebiendo chocolate caliente",
    "Un perro con un gorro de fiesta",
    "Un niño echando una carta con forma de corazón al buzón",
    "Dos personas chocando las manos después de terminar un rompecabezas",
    "Un conejo sosteniendo una linterna por la noche",
    "Una persona enseñando a bailar a un robot",
    "Un gato y un perro compartiendo un alféizar soleado",
    "Un niño haciendo un ángel de nieve",
    "Un zorrito llevando una nota de agradecimiento",
    "Una rana leyendo bajo una hoja",
    "Un ratón compartiendo una galleta con un amigo",
    "Un sol arropando a una estrella",
    "Un pato remando junto a un barco de papel",
    "Un niño pegando una pegatina en un cuaderno",
    "Un conejo atando un lazo alrededor de un regalo",
    "Un koala saludando desde una fiambrera",
  ],
  "pt-br": [
    "Dois amigos fazendo panquecas",
    "Um astronauta sonolento descansando na lua",
    "Um avô ou avó ensinando uma criança a pescar",
    "Um gato de capa de chuva dividindo o guarda-chuva com um passarinho",
    "Um cachorro oferecendo uma florzinha a um gato",
    "Dois irmãos construindo uma cabana de cobertores",
    "Uma pessoa aquecendo as duas mãos em volta de uma caneca fumegante",
    "Uma criança correndo com uma pipa",
    "Dois gatos refazendo um beijo de super-herói de cabeça para baixo",
    "Um pequeno chef mexendo uma panela enorme de sopa",
    "Um urso lendo uma história de dormir para um coelho",
    "Um casal dançando na cozinha",
    "Um pinguim carregando um bolo de aniversário",
    "Uma pessoa responsável amarrando o cadarço de uma criança",
    "Dois amigos tirando uma selfie engraçada",
    "Um gato regando três florzinhas",
    "Um cachorro dormindo debaixo da escrivaninha",
    "Uma pessoa dando um cachecol quentinho para alguém",
    "Duas crianças pulando numa poça",
    "Um coelho pintando um quadrinho",
    "Um super-herói preparando o café da manhã",
    "Uma pessoa acenando pela janela do trem",
    "Dois amigos dividindo um par de fones de ouvido",
    "Um gato tentando alcançar uma folha caindo",
    "Uma criança abraçando um ursão de pelúcia",
    "Um casal observando as estrelas do terraço",
    "Um cachorro esperando ao lado de uma cesta de piquenique",
    "Uma pessoa plantando uma arvorezinha",
    "Dois passarinhos construindo um ninho juntos",
    "Uma confeiteira apresentando um cupcake perfeito",
    "Uma criança ajudando um caracol a atravessar o caminho",
    "Dois amigos jogando um jogo de tabuleiro",
    "Um gato dormindo sobre um livro aberto",
    "Uma pessoa carregando compras na chuva",
    "Um fantasminha tomando chocolate quente",
    "Um cachorro usando chapéu de festa",
    "Uma criança colocando no correio uma carta em forma de coração",
    "Duas pessoas batendo as mãos depois de terminar um quebra-cabeça",
    "Um coelho segurando uma lanterna à noite",
    "Uma pessoa ensinando um robô a dançar",
    "Um gato e um cachorro dividindo um parapeito ensolarado",
    "Uma criança fazendo um anjo na neve",
    "Uma raposinha carregando um bilhete de agradecimento",
    "Um sapo lendo debaixo de uma folha",
    "Um ratinho dividindo um biscoito com um amigo",
    "Um sol colocando uma estrela na cama",
    "Um pato remando ao lado de um barquinho de papel",
    "Uma criança colando um adesivo num caderno",
    "Um coelho amarrando uma fita num presente",
    "Um coala acenando de dentro de uma lancheira",
  ],
  it: [
    "Due amici preparano i pancake",
    "Un astronauta assonnato riposa sulla luna",
    "Un nonno o una nonna insegna a un bambino a pescare",
    "Un gatto con l’impermeabile condivide l’ombrello con un uccellino",
    "Un cane offre un piccolo fiore a un gatto",
    "Due fratelli costruiscono un rifugio con le coperte",
    "Una persona scalda entrambe le mani intorno a una tazza fumante",
    "Un bambino corre con un aquilone",
    "Due gatti ricreano un bacio da supereroi a testa in giù",
    "Un piccolo chef mescola una pentola enorme di zuppa",
    "Un orso legge una storia della buonanotte a un coniglio",
    "Una coppia balla in cucina",
    "Un pinguino porta una torta di compleanno",
    "Un genitore allaccia la scarpa di un bambino",
    "Due amici si fanno un selfie buffo",
    "Un gatto annaffia tre piccoli fiori",
    "Un cane dorme sotto una scrivania",
    "Una persona regala a qualcuno una sciarpa calda",
    "Due bambini saltano in una pozzanghera",
    "Un coniglio dipinge un piccolo quadro",
    "Un supereroe prepara la colazione",
    "Una persona saluta dal finestrino del treno",
    "Due amici condividono un paio di cuffie",
    "Un gatto cerca di afferrare una foglia che cade",
    "Un bambino abbraccia un grande orso di peluche",
    "Una coppia guarda le stelle da un tetto",
    "Un cane aspetta accanto a un cestino da picnic",
    "Una persona pianta un alberello",
    "Due uccelli costruiscono insieme un nido",
    "Un pasticciere presenta un cupcake perfetto",
    "Un bambino aiuta una lumaca ad attraversare il sentiero",
    "Due amici giocano a un gioco da tavolo",
    "Un gatto dorme su un libro aperto",
    "Una persona porta la spesa sotto la pioggia",
    "Un piccolo fantasma beve cioccolata calda",
    "Un cane indossa un cappello da festa",
    "Un bambino imbuca una lettera a forma di cuore",
    "Due persone si danno il cinque dopo aver finito un puzzle",
    "Un coniglio tiene una lanterna di notte",
    "Una persona insegna a un robot a ballare",
    "Un gatto e un cane condividono un davanzale al sole",
    "Un bambino fa un angelo nella neve",
    "Una piccola volpe porta un biglietto di ringraziamento",
    "Una rana legge sotto una foglia",
    "Un topo condivide un biscotto con un amico",
    "Un sole mette una stella a letto",
    "Un’anatra rema accanto a una barchetta di carta",
    "Un bambino attacca un adesivo su un quaderno",
    "Un coniglio annoda un nastro intorno a un regalo",
    "Un koala saluta da una scatola per il pranzo",
  ],
  ja: [
    "2人の友だちがパンケーキを焼いている",
    "眠そうな宇宙飛行士が月で休んでいる",
    "祖父母が子どもに釣りを教えている",
    "レインコート姿の猫が小さな鳥と傘を分け合っている",
    "犬が猫に小さな花をプレゼントしている",
    "きょうだい2人が毛布の秘密基地を作っている",
    "人が湯気の立つマグカップで両手を温めている",
    "子どもが凧を持って走っている",
    "2匹の猫が逆さまのスーパーヒーローのキスをまねている",
    "小さなシェフが大きなスープ鍋をかき混ぜている",
    "クマがウサギにおやすみ前の物語を読んでいる",
    "カップルがキッチンで踊っている",
    "ペンギンが誕生日ケーキを運んでいる",
    "親が子どもの靴ひもを結んでいる",
    "友だち2人がおもしろい自撮りをしている",
    "猫が3輪の小さな花に水をあげている",
    "犬が机の下で眠っている",
    "人が誰かに暖かいマフラーを渡している",
    "子ども2人が1つの水たまりで跳ねている",
    "ウサギが小さな絵を描いている",
    "スーパーヒーローが朝ごはんを作っている",
    "人が電車の窓から手を振っている",
    "友だち2人が1つのヘッドホンを分け合っている",
    "猫が落ち葉に手を伸ばしている",
    "子どもが大きなテディベアを抱きしめている",
    "カップルが屋上から星を眺めている",
    "犬がピクニックバスケットの隣で待っている",
    "人が小さな木を植えている",
    "2羽の鳥が一緒に巣を作っている",
    "パン職人が完璧なカップケーキを見せている",
    "子どもがカタツムリの道渡りを手伝っている",
    "友だち2人がボードゲームをしている",
    "猫が開いた本の上で眠っている",
    "人が雨の中で買い物袋を運んでいる",
    "小さなおばけがホットチョコレートを飲んでいる",
    "犬がパーティーハットをかぶっている",
    "子どもがハート形の手紙を投函している",
    "2人がパズルを完成させてハイタッチしている",
    "ウサギが夜にランタンを持っている",
    "人がロボットにダンスを教えている",
    "猫と犬が日なたの窓辺を分け合っている",
    "子どもが雪の天使を作っている",
    "小さなキツネがお礼のメモを運んでいる",
    "カエルが葉っぱの下で本を読んでいる",
    "ネズミが友だちとクッキーを分け合っている",
    "太陽が星をベッドに寝かしつけている",
    "アヒルが紙の船のそばを泳いでいる",
    "子どもがノートにシールを貼っている",
    "ウサギがプレゼントにリボンを結んでいる",
    "コアラがお弁当箱から手を振っている",
  ],
  ko: [
    "친구 둘이 팬케이크를 굽고 있어요",
    "졸린 우주비행사가 달에서 쉬고 있어요",
    "조부모가 아이에게 낚시를 가르치고 있어요",
    "비옷을 입은 고양이가 작은 새와 우산을 함께 쓰고 있어요",
    "강아지가 고양이에게 작은 꽃을 건네고 있어요",
    "형제자매가 담요 요새를 만들고 있어요",
    "사람이 김이 나는 머그컵에 두 손을 녹이고 있어요",
    "아이가 연을 들고 달리고 있어요",
    "고양이 두 마리가 거꾸로 된 슈퍼히어로 키스를 따라 하고 있어요",
    "작은 요리사가 커다란 수프 냄비를 저어요",
    "곰이 토끼에게 잠자리 이야기를 읽어 주고 있어요",
    "연인이 부엌에서 춤추고 있어요",
    "펭귄이 생일 케이크를 나르고 있어요",
    "부모가 아이의 신발 끈을 묶어 주고 있어요",
    "친구 둘이 우스운 셀카를 찍고 있어요",
    "고양이가 작은 꽃 세 송이에 물을 주고 있어요",
    "강아지가 책상 아래에서 자고 있어요",
    "누군가가 다른 사람에게 따뜻한 목도리를 건네고 있어요",
    "아이 둘이 물웅덩이 하나에서 뛰고 있어요",
    "토끼가 작은 그림을 그리고 있어요",
    "슈퍼히어로가 아침을 만들고 있어요",
    "사람이 기차 창문에서 손을 흔들고 있어요",
    "친구 둘이 헤드폰 한 쌍을 나눠 쓰고 있어요",
    "고양이가 떨어지는 나뭇잎에 손을 뻗고 있어요",
    "아이가 커다란 곰 인형을 안고 있어요",
    "연인이 옥상에서 별을 바라보고 있어요",
    "강아지가 피크닉 바구니 옆에서 기다리고 있어요",
    "사람이 작은 나무를 심고 있어요",
    "새 두 마리가 함께 둥지를 만들고 있어요",
    "제빵사가 완벽한 컵케이크 하나를 보여 주고 있어요",
    "아이가 달팽이가 길을 건너도록 도와주고 있어요",
    "친구 둘이 보드게임을 하고 있어요",
    "고양이가 펼쳐진 책 위에서 자고 있어요",
    "사람이 빗속에서 장을 들고 가고 있어요",
    "작은 유령이 핫초코를 마시고 있어요",
    "강아지가 파티 모자를 쓰고 있어요",
    "아이가 하트 모양 편지를 부치고 있어요",
    "두 사람이 퍼즐을 끝내고 하이파이브하고 있어요",
    "토끼가 밤에 랜턴을 들고 있어요",
    "사람이 로봇에게 춤을 가르치고 있어요",
    "고양이와 강아지가 햇살 드는 창턱을 함께 쓰고 있어요",
    "아이가 눈밭에 눈 천사를 만들고 있어요",
    "작은 여우가 감사 쪽지를 들고 있어요",
    "개구리가 나뭇잎 아래에서 책을 읽고 있어요",
    "생쥐가 친구와 쿠키를 나눠 먹고 있어요",
    "해가 별을 침대에 눕혀 주고 있어요",
    "오리가 종이배 옆에서 노를 저어요",
    "아이가 공책에 스티커를 붙이고 있어요",
    "토끼가 선물에 리본을 묶고 있어요",
    "코알라가 도시락에서 손을 흔들고 있어요",
  ],
  ar: [
    "صديقان يخبزان الفطائر",
    "رائد فضاء نعسان يستريح على القمر",
    "جد أو جدة يعلّم طفلًا الصيد",
    "قطة ترتدي معطفًا للمطر وتتقاسم مظلة مع طائر صغير",
    "كلب يقدم زهرة صغيرة لقطة",
    "شقيقان يبنيان حصنًا من البطانيات",
    "شخص يدفئ يديه حول كوب يتصاعد منه البخار",
    "طفل يركض بطائرة ورقية",
    "قطتان تقلدان قبلة أبطال خارقين مقلوبة",
    "طاهٍ صغير يحرك قدر شوربة كبيرًا",
    "دب يقرأ قصة قبل النوم لأرنب",
    "زوجان يرقصان في المطبخ",
    "بطريق يحمل كعكة عيد ميلاد",
    "أحد الوالدين يربط رباط حذاء طفل",
    "صديقان يلتقطان صورة سيلفي مضحكة",
    "قطة تسقي ثلاث زهرات صغيرة",
    "كلب ينام تحت مكتب",
    "شخص يهدي آخر وشاحًا دافئًا",
    "طفلان يقفزان في بركة ماء واحدة",
    "أرنب يرسم لوحة صغيرة",
    "بطل خارق يحضّر الفطور",
    "شخص يلوّح من نافذة قطار",
    "صديقان يتشاركان سماعة واحدة",
    "قطة تمد يدها نحو ورقة ساقطة",
    "طفل يعانق دمية دب كبيرة",
    "زوجان يشاهدان النجوم من سطح منزل",
    "كلب ينتظر بجوار سلة نزهة",
    "شخص يزرع شجرة صغيرة",
    "عصفوران يبنيان عشًا معًا",
    "خباز يقدم كب كيك مثاليًا",
    "طفل يساعد حلزونًا على عبور الطريق",
    "صديقان يلعبان لعبة لوحية",
    "قطة تنام فوق كتاب مفتوح",
    "شخص يحمل مشتريات تحت المطر",
    "شبح صغير يشرب شوكولاتة ساخنة",
    "كلب يرتدي قبعة احتفالية",
    "طفل يرسل رسالة على شكل قلب",
    "شخصان يتصافحان بخفة بعد إكمال أحجية",
    "أرنب يحمل فانوسًا ليلًا",
    "شخص يعلّم روبوتًا الرقص",
    "قطة وكلب يتشاركان حافة نافذة مشمسة",
    "طفل يصنع ملاكًا في الثلج",
    "ثعلب صغير يحمل رسالة شكر",
    "ضفدع يقرأ تحت ورقة",
    "فأر يتقاسم كعكة مع صديق",
    "شمس تدس نجمة في السرير",
    "بطة تجدّف بجوار قارب ورقي",
    "طفل يضع ملصقًا على دفتر",
    "أرنب يربط شريطًا حول هدية",
    "كوالا يلوّح من صندوق الغداء",
  ],
} as const;

export type SceneSuggestionLocale = keyof typeof SCENE_SUGGESTIONS_BY_LOCALE;
